# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Node.js version
  nodeVersion: '18.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install frontend dependencies'

- script: |
    npm run build
  displayName: 'Build frontend'
  env:
    VITE_API_BASE_URL: $(VITE_API_BASE_URL)
    VITE_ADMIN_USERNAME: $(VITE_ADMIN_USERNAME)
    VITE_ADMIN_PASSWORD: $(VITE_ADMIN_PASSWORD)

- script: |
    cd backend
    npm ci
  displayName: 'Install backend dependencies'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: '$(azureServiceConnectionId)'
    appType: 'webApp'
    appName: '$(appName)'
    package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
